language: python

python:
  - '3.2'
  - '3.3'
  - '3.4'
  - 'pypy3'

install:
  - python setup.py install
  - pip install peewee
  - pip install pyyaml
  - pip install redis

script:
  - python tests/run.py
