sudo: false
language: python

python:
  - '3.5'

install:
#  - python setup.py install
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov

script:
  - nosetests --with-coverage

after_success:
  - codecov